"use client";

import { useState, useCallback } from "react";
import { CheckCircle2, Download, FileText, Layers, TerminalSquare, LayoutGrid, Check, Sparkles, Rocket, ArrowRight, Code2, Copy, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

import type { Project } from "@/lib/schemas/project";
import { MarkdownViewer } from "../ui/markdown-viewer";
import { StructuredDataViewer } from "../ui/structured-data-viewer";

interface CompleteStageProps {
  project: Project;
}

type DashboardView = "overview" | "brief" | "architecture" | "execution";

export function CompleteStage({ project }: CompleteStageProps) {
  const [activeView, setActiveView] = useState<DashboardView>("overview");
  const [isExporting, setIsExporting] = useState(false);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  // Track expanded state for individual prompts (open first one by default)
  const [expandedPrompts, setExpandedPrompts] = useState<Record<number, boolean>>({ 0: true });

  const togglePrompt = (idx: number) => {
    setExpandedPrompts(prev => ({
      ...prev,
      [idx]: !prev[idx]
    }));
  };

  const handleCopy = useCallback((text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => setCopiedSection(null), 2000);
  }, []);

  const handleExportAll = () => {
    setIsExporting(true);

    let content = `# Project Alignment File: ${project.title || 'Untitled Project'}\n\n`;
    content += `> Generated by Alignr\n\n---\n\n`;

    // 1. Business Brief
    content += `## 1. Business Brief\n\n`;
    content += `${project.businessBrief?.content || 'No brief recorded.'}\n\n---\n\n`;

    // 2. Architecture
    content += `## 2. Architecture Blueprint\n\n`;
    content += "```json\n";
    content += JSON.stringify(project.architectureBlueprint, null, 2);
    content += "\n```\n\n---\n\n";

    // 3. Execution Package
    content += `## 3. Execution Package\n\n`;
    const exec = project.executionPackage;
    if (exec) {
      content += `### Extracted Requirements\n`;
      exec.requirements.forEach(req => {
        content += `- ${req}\n`;
      });
      content += `\n### Sequential Coding Prompts\n`;
      exec.sequentialPrompts.forEach((prompt, idx) => {
        content += `#### Step ${idx + 1}\n\n\`\`\`text\n${prompt}\n\`\`\`\n\n`;
      });
    } else {
      content += `No execution package recorded.\n`;
    }

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.title ? project.title.toLowerCase().replace(/\s+/g, '-') : 'project'}-alignr-export.md`;
    a.click();
    URL.revokeObjectURL(url);

    setTimeout(() => setIsExporting(false), 2000);
  };

  const navItems = [
    { id: "overview", label: "Project Overview", icon: LayoutGrid },
    { id: "brief", label: "Business Brief", icon: FileText },
    { id: "architecture", label: "System Architecture", icon: Layers },
    { id: "execution", label: "Execution Prompts", icon: TerminalSquare },
  ] as const;

  // --- Fixed Data Extraction based on your strict Zod Schema ---
  const arch = project.architectureBlueprint;
  const techStack = arch?.techStack || [];
  const screensCount = arch?.frontendScreens?.length || 0;
  const features = arch?.features || [];
  const promptsCount = project.executionPackage?.sequentialPrompts?.length || 0;

  return (
    <div className="flex h-full flex-col bg-bg">
      {/* Top Header */}
      <div className="flex items-center justify-between border-b border-border bg-bg p-4 sticky top-0 z-10">
        <div>
          <h2 className="text-lg font-semibold text-fg flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-accent" />
            Project Deployed
          </h2>
          <p className="text-sm text-fg-muted mt-0.5">
            All artifacts generated and ready for use.
          </p>
        </div>
        <Button
          onClick={handleExportAll}
          disabled={isExporting}
          className="gap-2"
        >
          {isExporting ? <Check className="h-4 w-4" /> : <Download className="h-4 w-4" />}
          {isExporting ? 'Exported' : 'Export Full Project'}
        </Button>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar Navigation */}
        <div className="w-64 border-r border-border bg-bg-secondary/30 p-4 flex flex-col gap-2 overflow-y-auto">
          <div className="text-xs font-semibold text-fg-muted uppercase tracking-wider mb-2 px-3">
            Dashboard Menu
          </div>
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = activeView === item.id;
            return (
              <button
                key={item.id}
                onClick={() => setActiveView(item.id)}
                className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-colors ${isActive
                    ? "bg-accent/10 text-accent"
                    : "text-fg-muted hover:bg-bg-secondary hover:text-fg"
                  }`}
              >
                <Icon className={`h-4 w-4 ${isActive ? "text-accent" : "text-fg-muted"}`} />
                {item.label}
              </button>
            );
          })}
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6 bg-bg">
          <div className="mx-auto max-w-5xl">

            {/* VIEW: OVERVIEW */}
            {activeView === "overview" && (
              <div className="space-y-6 animate-in fade-in duration-500">

                {/* 1. Hero & Pipeline */}
                <div className="rounded-xl border border-border bg-bg-secondary/20 p-8 shadow-sm relative overflow-hidden">
                  <div className="absolute top-0 right-0 p-8 opacity-5">
                    <Rocket className="w-48 h-48" />
                  </div>
                  <div className="relative z-10 flex flex-col items-center text-center">
                    <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-success/30 bg-success/10 px-3 py-1 text-sm font-medium text-success">
                      <CheckCircle2 className="h-4 w-4" />
                      System Ready for Execution
                    </div>
                    <h3 className="text-3xl font-bold text-fg tracking-tight mb-2">
                      {project.title || "Untitled Project"}
                    </h3>
                    <p className="text-base text-fg-muted max-w-lg mb-10">
                      Your business brief, architecture, and coding prompts have been fully synthesized.
                    </p>

                    {/* Progress Pipeline */}
                    <div className="w-full max-w-3xl relative">
                      <div className="absolute top-1/2 left-0 w-full h-[2px] bg-border -translate-y-1/2 -z-10 rounded-full">
                        <div className="h-full bg-success w-full rounded-full"></div>
                      </div>
                      <div className="flex justify-between items-center w-full">
                        {[
                          { label: "Discovery", icon: FileText },
                          { label: "Architecture", icon: Layers },
                          { label: "Prompts", icon: TerminalSquare },
                          { label: "Launch", icon: Rocket }
                        ].map((step, i) => (
                          <div key={i} className="flex flex-col items-center gap-2">
                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-bg border-2 border-success text-success shadow-[0_0_10px_rgba(34,197,94,0.2)]">
                              <step.icon className="h-4 w-4" />
                            </div>
                            <span className="text-xs font-semibold text-fg bg-bg px-1">{step.label}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>

                {/* 2. Key Metrics Grid */}
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                  <Card className="shadow-sm border-border">
                    <CardContent className="p-5 flex flex-col justify-between h-full">
                      <div className="flex items-center justify-between mb-4">
                        <span className="text-xs font-medium text-fg-muted uppercase tracking-wider">Tech Stack</span>
                        <Layers className="h-4 w-4 text-accent" />
                      </div>
                      <div>
                        <div className="text-2xl font-bold text-fg mb-2">{techStack.length} Technologies</div>
                        <div className="flex flex-wrap gap-1">
                          {techStack.slice(0, 3).map((tech, i) => (
                            <span key={i} className="text-[10px] font-semibold bg-bg-secondary text-fg px-1.5 py-0.5 rounded border border-border">
                              {tech}
                            </span>
                          ))}
                          {techStack.length > 3 && <span className="text-[10px] text-fg-muted px-1">+{techStack.length - 3}</span>}
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="shadow-sm border-border">
                    <CardContent className="p-5 flex flex-col justify-between h-full">
                      <div className="flex items-center justify-between mb-4">
                        <span className="text-xs font-medium text-fg-muted uppercase tracking-wider">Frontend</span>
                        <LayoutGrid className="h-4 w-4 text-accent" />
                      </div>
                      <div>
                        <div className="text-3xl font-bold text-fg mb-1">{screensCount}</div>
                        <p className="text-xs text-fg-muted font-medium">Distinct Screens/Pages</p>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="shadow-sm border-border">
                    <CardContent className="p-5 flex flex-col justify-between h-full">
                      <div className="flex items-center justify-between mb-4">
                        <span className="text-xs font-medium text-fg-muted uppercase tracking-wider">Execution</span>
                        <TerminalSquare className="h-4 w-4 text-accent" />
                      </div>
                      <div>
                        <div className="text-3xl font-bold text-fg mb-1">{promptsCount}</div>
                        <p className="text-xs text-fg-muted font-medium">Sequential AI Prompts</p>
                      </div>
                    </CardContent>
                  </Card>

                  <Card className="shadow-sm border-border">
                    <CardContent className="p-5 flex flex-col justify-between h-full">
                      <div className="flex items-center justify-between mb-4">
                        <span className="text-xs font-medium text-fg-muted uppercase tracking-wider">Export</span>
                        <Download className="h-4 w-4 text-accent" />
                      </div>
                      <div>
                        <Button onClick={handleExportAll} size="sm" className="w-full gap-2 font-semibold">
                          Download .md
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                {/* 3. Project DNA & Next Steps Row */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

                  {/* Core Features */}
                  <Card className="shadow-sm border-border flex flex-col">
                    <CardHeader className="bg-bg-secondary/30 pb-4 border-b border-border/50">
                      <CardTitle className="text-base flex items-center gap-2">
                        <Sparkles className="h-4 w-4 text-accent" />
                        Project Highlights
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="p-5 flex-1">
                      {features.length > 0 ? (
                        <ul className="space-y-3">
                          {features.slice(0, 4).map((feature, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-fg">
                              <CheckCircle2 className="h-4 w-4 text-success shrink-0 mt-0.5" />
                              <span className="leading-tight">{feature}</span>
                            </li>
                          ))}
                          {features.length > 4 && (
                            <li className="text-xs text-fg-muted italic pt-1">
                              + {features.length - 4} more features in architecture
                            </li>
                          )}
                        </ul>
                      ) : (
                        <p className="text-sm text-fg-muted">No specific features listed in the architecture plan.</p>
                      )}
                    </CardContent>
                  </Card>

                  {/* Launchpad / Next Steps */}
                  <Card className="shadow-sm border-accent/20 bg-accent/5 flex flex-col relative overflow-hidden">
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base flex items-center gap-2 text-accent">
                        <Code2 className="h-4 w-4" />
                        Developer Launchpad
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="p-5 pt-2 flex flex-col justify-between flex-1">
                      <p className="text-sm text-fg mb-4">
                        Your project is ready to be built. Follow these steps to begin development with your AI coding agent:
                      </p>
                      <div className="space-y-3">
                        <div className="flex items-center gap-3 bg-bg border border-border p-3 rounded-md">
                          <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/20 text-xs font-bold text-accent">1</div>
                          <p className="text-sm text-fg">Download the Full Project `.md` file.</p>
                        </div>
                        <div className="flex items-center gap-3 bg-bg border border-border p-3 rounded-md">
                          <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/20 text-xs font-bold text-accent">2</div>
                          <p className="text-sm text-fg">Open your Coding AI (Cursor, Claude, Devin).</p>
                        </div>
                        <div className="flex items-center gap-3 bg-bg border border-border p-3 rounded-md cursor-pointer hover:border-accent transition-colors" onClick={() => setActiveView("execution")}>
                          <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/20 text-xs font-bold text-accent">3</div>
                          <p className="text-sm text-fg font-medium">Copy Prompts sequentially <ArrowRight className="h-3 w-3 inline ml-1" /></p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            )}

            {/* VIEW: BUSINESS BRIEF */}
            {activeView === "brief" && (
              <div className="animate-in fade-in duration-300">
                <Card className="border-border shadow-sm">
                  <CardHeader className="border-b border-border/50 bg-bg-secondary/50 pb-4">
                    <div className="flex items-center gap-2">
                      <FileText className="h-5 w-5 text-accent" />
                      <CardTitle className="text-base">Business Brief</CardTitle>
                    </div>
                    <CardDescription>Origin: Discovery Phase</CardDescription>
                  </CardHeader>
                  <CardContent className="p-6">
                    <MarkdownViewer content={project.businessBrief?.content || 'No business brief found.'} />
                  </CardContent>
                </Card>
              </div>
            )}

            {/* VIEW: ARCHITECTURE */}
            {activeView === "architecture" && (
              <div className="animate-in fade-in duration-300">
                <Card className="border-border shadow-sm">
                  <CardHeader className="border-b border-border/50 bg-bg-secondary/50 pb-4">
                    <div className="flex items-center gap-2">
                      <Layers className="h-5 w-5 text-accent" />
                      <CardTitle className="text-base">Architecture Blueprint</CardTitle>
                    </div>
                    <CardDescription>Origin: Planning Phase</CardDescription>
                  </CardHeader>
                  <CardContent className="p-6 bg-bg">
                    <StructuredDataViewer data={project.architectureBlueprint} />
                  </CardContent>
                </Card>
              </div>
            )}

            {/* VIEW: EXECUTION */}
            {activeView === "execution" && (
              <div className="space-y-6 animate-in fade-in duration-300">
                <Card className="border-border shadow-sm">
                  <CardHeader className="flex flex-row items-center justify-between border-b border-border/50 bg-bg-secondary/50 pb-4">
                    <div>
                      <div className="flex items-center gap-2">
                        <TerminalSquare className="h-5 w-5 text-accent" />
                        <CardTitle className="text-base">Sequential Prompts</CardTitle>
                      </div>
                      <CardDescription className="mt-1">Output: Ready for your external Coding Agent</CardDescription>
                    </div>
                    <Button
                      variant="secondary"
                      size="sm"
                      className="gap-2"
                      onClick={() => {
                        const allPrompts = project.executionPackage?.sequentialPrompts.join('\n\n') || '';
                        handleCopy(allPrompts, 'all_prompts');
                      }}
                    >
                      {copiedSection === 'all_prompts' ? <Check className="h-4 w-4 text-success" /> : <Copy className="h-4 w-4" />}
                      Copy All
                    </Button>
                  </CardHeader>
                  <CardContent className="space-y-4 pt-6 bg-bg">
                    {project.executionPackage?.sequentialPrompts.map((prompt, idx) => {
                      const isExpanded = !!expandedPrompts[idx];

                      return (
                        <div key={idx} className="group rounded-lg border border-border bg-bg-secondary overflow-hidden transition-colors hover:border-accent/40">

                          {/* Clickable Header */}
                          <div
                            className="flex flex-row items-center justify-between p-4 cursor-pointer bg-bg-secondary hover:bg-bg-secondary/80 transition-colors"
                            onClick={() => togglePrompt(idx)}
                          >
                            <div className="flex items-center gap-3">
                              <span className="flex h-7 w-7 items-center justify-center rounded-full bg-accent/10 text-xs font-bold text-accent">
                                {idx + 1}
                              </span>
                              <h4 className="text-sm font-semibold text-fg">Execution Step {idx + 1}</h4>
                            </div>

                            <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                              <Button
                                variant="outline"
                                size="sm"
                                className="h-8 w-8 p-0 bg-bg shadow-sm hover:border-accent"
                                onClick={() => handleCopy(prompt, `prompt_${idx}`)}
                                title="Copy this prompt"
                              >
                                {copiedSection === `prompt_${idx}` ? <Check className="h-4 w-4 text-success" /> : <Copy className="h-4 w-4 text-fg-muted" />}
                              </Button>
                              <div className="flex h-8 w-8 items-center justify-center text-fg-muted pointer-events-none">
                                {isExpanded ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
                              </div>
                            </div>
                          </div>

                          {/* Collapsible Content */}
                          {isExpanded && (
                            <div className="p-5 pt-0 border-t border-border/50 bg-bg">
                              <div className="mt-4 rounded-md bg-bg-secondary/30 p-5 border border-border/50 shadow-inner overflow-x-auto">
                                <MarkdownViewer content={prompt} />
                              </div>
                            </div>
                          )}
                        </div>
                      );
                    })}
                    {!project.executionPackage?.sequentialPrompts.length && (
                      <p className="text-sm text-fg-muted text-center py-8">No prompts generated yet.</p>
                    )}
                  </CardContent>
                </Card>
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
}