"use client";

import { Button } from "@/components/ui/button";
import { Sparkles, Bot } from "lucide-react";

export function TriggerUIVisualizerToolUI({
  callId,
  state,
  toolInput,
  toolOutput,
  errorText,
}: {
  callId: string;
  state: string;
  toolInput?: { screenName: string; associatedFeature: string };
  toolOutput?: { screenName: string; associatedFeature: string; mockCode: string; status: string };
  errorText?: string;
}) {
  switch (state) {
    case "input-streaming":
    case "input-available":
      return (
        <div key={callId} className="mt-2 p-4 bg-bg border border-accent/30 rounded-lg flex flex-col items-center justify-center space-y-3 py-8">
          <Sparkles className="h-6 w-6 text-accent animate-pulse" />
          <div className="text-sm font-medium text-fg">Generating UI Prototype for {toolInput?.screenName}…</div>
        </div>
      );
    case "output-available":
      return (
        <div key={callId} className="mt-2 space-y-3">
          <div className="p-4 bg-bg border border-accent/30 rounded-lg space-y-4">
            <div className="flex items-center justify-between">
              <div className="text-sm font-semibold text-fg flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-accent" />
                UI Prototype: {toolOutput?.screenName}
              </div>
              <span className="text-[10px] text-fg-muted font-mono px-1.5 py-0.5 bg-bg-secondary rounded border border-border">
                {toolOutput?.associatedFeature}
              </span>
            </div>
            
            <div className="rounded-md border border-border bg-white p-6 shadow-inner min-h-[200px] flex flex-col items-center justify-center text-center space-y-4">
              <div className="w-16 h-16 rounded-full bg-accent/10 flex items-center justify-center">
                <Bot className="h-8 w-8 text-accent" />
              </div>
              <div className="space-y-1">
                <h3 className="text-lg font-bold text-gray-900">{toolOutput?.screenName}</h3>
                <p className="text-xs text-gray-500 max-w-[200px]">
                  This is a mock visualization of the screen code generated by the agent.
                </p>
              </div>
              <Button size="sm" variant="outline" className="text-gray-900 border-gray-300">
                Mock Interactive Element
              </Button>
            </div>

            <div className="text-[10px] font-mono bg-bg-secondary p-3 rounded border border-border text-fg-muted overflow-x-auto max-h-40">
              <pre>{toolOutput?.mockCode}</pre>
            </div>
          </div>
        </div>
      );
    case "output-error":
      return (
        <div key={callId} className="text-destructive text-xs">
          Error: {errorText}
        </div>
      );
    default:
      return null;
  }
}
