import { z } from "zod";

// Schema for the interview questions generated by the Business Analyst
// to be rendered as dynamic forms in the UI.
export const interviewQuestionSchema = z.object({
  id: z.string().describe("A unique short identifier for this question, e.g. 'q1_problem', 'q2_users'"),
  question: z.string().describe("The question text to display to the user"),
  type: z.enum(["text", "textarea", "single-choice", "multiple-choice"]).describe("The type of form input to render"),
  options: z.array(z.string()).optional().describe("Options for single-choice or multiple-choice questions"),
});

export const interviewQuestionsSchema = z.object({
  questions: z.array(interviewQuestionSchema).describe("An ordered array of questions to be rendered by the UI"),
});

// Schema for the final business brief outputted when the agent feels it has gathered enough context.
export const businessBriefSchema = z.object({
  content: z.string().describe("The unstructured markdown business brief"),
});

export type InterviewQuestions = z.infer<typeof interviewQuestionsSchema>;
export type BusinessBrief = z.infer<typeof businessBriefSchema>;
