import { z } from "zod";
import { projectStageSchema } from "./chat";
import { businessBriefSchema } from "./stages/business-analyst";
import { architecturePlanSchema } from "./stages/software-planner";
import { uiPrototypeSchema } from "./stages/ui-coder";
import { executionPackageSchema } from "./stages/critique";

export const projectSchema = z.object({
  _id: z.string().describe("MongoDB ObjectId as a string"),
  userId: z.string().describe("MongoDB ObjectId mapping to the User"),
  title: z.string().describe("The title of the project"),
  currentStage: projectStageSchema.describe("The current development stage of the project"),
  
  // Agent stage outputs
  businessBrief: businessBriefSchema.optional().describe("The final business brief produced by the Business Analyst"),
  architectureBlueprint: architecturePlanSchema.optional().describe("The structured architecture plan from the Software Planner"),
  uiPrototypes: uiPrototypeSchema.optional().describe("The generated UI components from the UI Coder"),
  executionPackage: executionPackageSchema.optional().describe("The final execution package generated by the Critique & Parser phase"),
  
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type Project = z.infer<typeof projectSchema>;
